name: Music Assistant Server (dev)
version: 1.0.8
slug: music_assistant_dev
description: Development (nightly) version of Music Assistant.
  Do not install this add-on unless you're specifically asked or a developer!
  This add-on installs the latest version from the main branch directly from git at startup.
url: https://music-assistant.io
arch:
  - amd64
  - aarch64
homeassistant_api: true
auth_api: true
host_network: true
ingress: true
ingress_port: 8095
panel_icon: mdi:play-circle
panel_title: Music Assistant
panel_admin: false
uart: false
map:
  - media:rw
init: false
advanced: false
stage: experimental
tmpfs: true
options:
  log_level: info
  branch: main
  safe_mode: false
schema:
  log_level: list(debug|info|warning|error)
  branch: str
  safe_mode: bool
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
