advanced: false
arch:
- amd64
- aarch64
auth_api: true
description: BETA version of Music Assistant. Install this version if you want to
  keep up with the latest and greatest and don't mind some beta testing. Follow us
  on discord to report and discuss feedback!
homeassistant_api: true
host_network: true
image: ghcr.io/music-assistant/server
ingress: true
ingress_port: 8095
init: false
map:
- media:rw
name: Music Assistant BETA
options:
  enable_uvloop: false
  log_level: info
panel_admin: false
panel_icon: mdi:play-circle
panel_title: Music Assistant
privileged:
- SYS_ADMIN
- DAC_READ_SEARCH
schema:
  enable_uvloop: bool
  log_level: list(debug|info|warning|error)
slug: music_assistant_beta
stage: stable
tmpfs: true
uart: false
url: https://github.com/music-assistant/hass-music-assistant
version: 2.0.0b74
