---
url: https://github.com/music-assistant/hass-music-assistant
arch:
- amd64
- aarch64
homeassistant_api: true
auth_api: true
host_network: true
ingress: true
ingress_port: 8095
panel_icon: mdi:play-circle
uart: false
ports:
  8095/tcp: null
map:
- media:rw
init: false
name: Music Assistant
version: "2.0.0b3"
slug: music_assistant
description: Music Assistant is a music library manager for your offline and online music sources, combined with the power of Home Assistant to easily stream your favourite music to a wide range of supported players.
image: ghcr.io/music-assistant/server
